docs_dir: "docs"
site_name: 安防知识
site_description: 安防视频监控知识
site_author: 天一生水
site_url: !ENV SITE_URL
repo_name: 'littleyz/ipc-docs'
repo_url: 'https://github.com/littleyz/ipc-docs'

# Copyright
copyright: "Copyright &copy; anfangzhishi.com"

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github 
  logo: https://cdn.ipc.name/wp-content/uploads/2021/10/cropped-logo-t.png
  favicon: 'assets/smartdns.png'
  language: 'zh'
  include_sidebar: false
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.path
    # - navigation.prune
    # - navigation.instant
    - navigation.indexes
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - toc.follow
    # - content.code.copy
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate


plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  generator: false

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - 首页: 'index.md'
  - 摄像机方案: 
    - 模组: 'ipc/module/list.md'
    - SoC:
      - 联咏Novatek: 'ipc/soc/nt.md'
      - 智源Grain Media: 'ipc/soc/gm.md'
      - 晨星Mstar: 'ipc/soc/mstar.md'
      - 星宸SigmaStar: 'ipc/soc/sstar.md'
      - 海思Hisilicon: 'ipc/soc/hi.md'
      - 富瀚Fullhan: 'ipc/soc/fh.md'
      - 安凯Anyka: 'ipc/soc/ak.md'
      - 国科Goke: 'ipc/soc/gk.md'
      - 君正ingenic: 'ipc/soc/t.md'
      - 安霸Ambarella: 'ipc/soc/a.md'
      - 德州仪器Ti: 'ipc/soc/ti.md'
      - 瑞昱Realtek: 'ipc/soc/rt.md'
      - 瑞芯微Rockchip: 'ipc/soc/rk.md'
      - 齐感SensLab: 'ipc/soc/qg.md'
      - 雄迈Xiongmai: 'ipc/soc/xm.md'
      - 爱芯元智Axera: 'ipc/soc/ax.md'
    - 传感器: 'ipc/sensor/sony.md'
    - ISP: 'ipc/isp/asus.md'
    - Wi-Fi: 'ipc/wifi/install/wsl.md'
  - 安防厂商:
    - 基本配置: 'config/basic-config.md'
    - 服务端配置: 'config/server-config.md'
    - 缓存设置: 'config/cache.md'
    - 屏蔽广告: 'config/ad-block.md'
    - 双栈优选: 'config/dualstack.md'
    - 禁用IPV6: 'config/block-ipv6.md'
  - 资料下载: 'configuration.md'
  - 关于: 'faq.md'
